### ISSUE TITLE
Add a new wallet

### ISSUE THREAD

**Issue by Warsten** [cyclone-github/atomic_pwn#3]
Hello. I don't know where to write to you, I decided to write here as I didn't see your contacts, sorry. I would like you to make a program to bruteforce Bitget wallet (Chrome browser extension) , they have a very similar hash with Atomic, starting with “U2FsdGVVkX1...”. But most likely the algorithm is different, because I can't recover the wallet having the exact password to test. It doesn't crack it.

**Comment by cyclone-github** [comment]
You can post a request with the wallet details at: https://forum.hashpwn.net
