### ISSUE TITLE
Module hashcat

### ISSUE THREAD

**Issue by PyluOtBabylu** [cyclone-github/atomic_pwn#4]
hi, i was able to implement a decoder in c# in a couple of lines a long time ago, but i have problems with integration and programming the core for hashcat, maybe we can do it together?

**Comment by cyclone-github** [comment]
Atomic wallets have previously been requested on hashcat's github: https://github.com/hashcat/hashcat/issues/3818

If you wish to collab with other users on writing a custom hashcat kernel, feel free to post here: https://forum.hashpwn.net
